fir=input('Input your first number:')
sec=input('Input your second number:')
thi=input('Input your third number:')
fou=input('Input your fourth number:')
fiv=input('Input your fiveth number:')
a=float(fir)
b=complex(fir)
c=float(sec)
d=complex(sec)
e=float(thi)
f=complex(thi)
g=float(fou)
i=complex(fou)
k=float(fiv)
l=complex(fiv)
print('float of %s eqaul '%fir,a)
print('complex of %s eqaul '%fir,b)
print('float of %s eqaul '%sec,c)
print('complex of %s eqaul '%sec,d)  
print('float of %s eqaul '%thi,e)
print('complex of %s eqaul '%thi,f)  
print('float of %s eqaul '%fou,g)
print('complex of %s eqaul '%fou,i)  
print('float of %s eqaul '%fiv,k)
print('complex of %s eqaul '%fiv,l)    