print("----------------------------")
print("produce show picked progarm")
print("----------------------------")
S_1=input("pick up 1 st      ")
S_2=input("pick up 2 nd      ")
S_3=input("pick up 3 rd      ")
S_4=input("pick up 4 th      ")
S_5=input("pick up 5 th      ")
produce=[S_1,S_2,S_3,S_4,S_5]
print("produce are picked")
print("1.",produce[0])
print("2.",produce[1])
print("3.",produce[2])
print("4.",produce[3])
print("5.",produce[4])
